###################################################################

# Created by write_sdc on Wed Nov 23 20:25:27 2022

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 4 [current_design]
set_max_area 0
set_driving_cell -lib_cell INVX1TS [get_ports clk]
set_driving_cell -lib_cell INVX1TS [get_ports reset]
set_driving_cell -lib_cell INVX1TS [get_ports {x1_bit[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x1_bit[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x1_bit[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x1_bit[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x1_bit[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x1_bit[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x1_bit[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x1_bit[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x2_bit[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x2_bit[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x2_bit[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x2_bit[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x2_bit[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x2_bit[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x2_bit[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x2_bit[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x3_bit[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x3_bit[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x3_bit[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x3_bit[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x3_bit[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x3_bit[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x3_bit[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x3_bit[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x4_bit[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x4_bit[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x4_bit[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x4_bit[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x4_bit[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x4_bit[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x4_bit[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x4_bit[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x5_bit[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x5_bit[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x5_bit[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x5_bit[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x5_bit[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x5_bit[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x5_bit[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x5_bit[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x6_bit[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x6_bit[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x6_bit[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x6_bit[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x6_bit[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x6_bit[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x6_bit[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x6_bit[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x7_bit[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x7_bit[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x7_bit[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x7_bit[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x7_bit[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x7_bit[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x7_bit[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x7_bit[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x8_bit[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x8_bit[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x8_bit[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x8_bit[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x8_bit[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x8_bit[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x8_bit[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {x8_bit[0]}]
set_load -pin_load 0.05 [get_ports {sum[31]}]
set_load -pin_load 0.05 [get_ports {sum[30]}]
set_load -pin_load 0.05 [get_ports {sum[29]}]
set_load -pin_load 0.05 [get_ports {sum[28]}]
set_load -pin_load 0.05 [get_ports {sum[27]}]
set_load -pin_load 0.05 [get_ports {sum[26]}]
set_load -pin_load 0.05 [get_ports {sum[25]}]
set_load -pin_load 0.05 [get_ports {sum[24]}]
set_load -pin_load 0.05 [get_ports {sum[23]}]
set_load -pin_load 0.05 [get_ports {sum[22]}]
set_load -pin_load 0.05 [get_ports {sum[21]}]
set_load -pin_load 0.05 [get_ports {sum[20]}]
set_load -pin_load 0.05 [get_ports {sum[19]}]
set_load -pin_load 0.05 [get_ports {sum[18]}]
set_load -pin_load 0.05 [get_ports {sum[17]}]
set_load -pin_load 0.05 [get_ports {sum[16]}]
set_load -pin_load 0.05 [get_ports {sum[15]}]
set_load -pin_load 0.05 [get_ports {sum[14]}]
set_load -pin_load 0.05 [get_ports {sum[13]}]
set_load -pin_load 0.05 [get_ports {sum[12]}]
set_load -pin_load 0.05 [get_ports {sum[11]}]
set_load -pin_load 0.05 [get_ports {sum[10]}]
set_load -pin_load 0.05 [get_ports {sum[9]}]
set_load -pin_load 0.05 [get_ports {sum[8]}]
set_load -pin_load 0.05 [get_ports {sum[7]}]
set_load -pin_load 0.05 [get_ports {sum[6]}]
set_load -pin_load 0.05 [get_ports {sum[5]}]
set_load -pin_load 0.05 [get_ports {sum[4]}]
set_load -pin_load 0.05 [get_ports {sum[3]}]
set_load -pin_load 0.05 [get_ports {sum[2]}]
set_load -pin_load 0.05 [get_ports {sum[1]}]
set_load -pin_load 0.05 [get_ports {sum[0]}]
set_max_capacitance 0.005 [get_ports clk]
set_max_capacitance 0.005 [get_ports reset]
set_max_capacitance 0.005 [get_ports {x1_bit[7]}]
set_max_capacitance 0.005 [get_ports {x1_bit[6]}]
set_max_capacitance 0.005 [get_ports {x1_bit[5]}]
set_max_capacitance 0.005 [get_ports {x1_bit[4]}]
set_max_capacitance 0.005 [get_ports {x1_bit[3]}]
set_max_capacitance 0.005 [get_ports {x1_bit[2]}]
set_max_capacitance 0.005 [get_ports {x1_bit[1]}]
set_max_capacitance 0.005 [get_ports {x1_bit[0]}]
set_max_capacitance 0.005 [get_ports {x2_bit[7]}]
set_max_capacitance 0.005 [get_ports {x2_bit[6]}]
set_max_capacitance 0.005 [get_ports {x2_bit[5]}]
set_max_capacitance 0.005 [get_ports {x2_bit[4]}]
set_max_capacitance 0.005 [get_ports {x2_bit[3]}]
set_max_capacitance 0.005 [get_ports {x2_bit[2]}]
set_max_capacitance 0.005 [get_ports {x2_bit[1]}]
set_max_capacitance 0.005 [get_ports {x2_bit[0]}]
set_max_capacitance 0.005 [get_ports {x3_bit[7]}]
set_max_capacitance 0.005 [get_ports {x3_bit[6]}]
set_max_capacitance 0.005 [get_ports {x3_bit[5]}]
set_max_capacitance 0.005 [get_ports {x3_bit[4]}]
set_max_capacitance 0.005 [get_ports {x3_bit[3]}]
set_max_capacitance 0.005 [get_ports {x3_bit[2]}]
set_max_capacitance 0.005 [get_ports {x3_bit[1]}]
set_max_capacitance 0.005 [get_ports {x3_bit[0]}]
set_max_capacitance 0.005 [get_ports {x4_bit[7]}]
set_max_capacitance 0.005 [get_ports {x4_bit[6]}]
set_max_capacitance 0.005 [get_ports {x4_bit[5]}]
set_max_capacitance 0.005 [get_ports {x4_bit[4]}]
set_max_capacitance 0.005 [get_ports {x4_bit[3]}]
set_max_capacitance 0.005 [get_ports {x4_bit[2]}]
set_max_capacitance 0.005 [get_ports {x4_bit[1]}]
set_max_capacitance 0.005 [get_ports {x4_bit[0]}]
set_max_capacitance 0.005 [get_ports {x5_bit[7]}]
set_max_capacitance 0.005 [get_ports {x5_bit[6]}]
set_max_capacitance 0.005 [get_ports {x5_bit[5]}]
set_max_capacitance 0.005 [get_ports {x5_bit[4]}]
set_max_capacitance 0.005 [get_ports {x5_bit[3]}]
set_max_capacitance 0.005 [get_ports {x5_bit[2]}]
set_max_capacitance 0.005 [get_ports {x5_bit[1]}]
set_max_capacitance 0.005 [get_ports {x5_bit[0]}]
set_max_capacitance 0.005 [get_ports {x6_bit[7]}]
set_max_capacitance 0.005 [get_ports {x6_bit[6]}]
set_max_capacitance 0.005 [get_ports {x6_bit[5]}]
set_max_capacitance 0.005 [get_ports {x6_bit[4]}]
set_max_capacitance 0.005 [get_ports {x6_bit[3]}]
set_max_capacitance 0.005 [get_ports {x6_bit[2]}]
set_max_capacitance 0.005 [get_ports {x6_bit[1]}]
set_max_capacitance 0.005 [get_ports {x6_bit[0]}]
set_max_capacitance 0.005 [get_ports {x7_bit[7]}]
set_max_capacitance 0.005 [get_ports {x7_bit[6]}]
set_max_capacitance 0.005 [get_ports {x7_bit[5]}]
set_max_capacitance 0.005 [get_ports {x7_bit[4]}]
set_max_capacitance 0.005 [get_ports {x7_bit[3]}]
set_max_capacitance 0.005 [get_ports {x7_bit[2]}]
set_max_capacitance 0.005 [get_ports {x7_bit[1]}]
set_max_capacitance 0.005 [get_ports {x7_bit[0]}]
set_max_capacitance 0.005 [get_ports {x8_bit[7]}]
set_max_capacitance 0.005 [get_ports {x8_bit[6]}]
set_max_capacitance 0.005 [get_ports {x8_bit[5]}]
set_max_capacitance 0.005 [get_ports {x8_bit[4]}]
set_max_capacitance 0.005 [get_ports {x8_bit[3]}]
set_max_capacitance 0.005 [get_ports {x8_bit[2]}]
set_max_capacitance 0.005 [get_ports {x8_bit[1]}]
set_max_capacitance 0.005 [get_ports {x8_bit[0]}]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports reset]
set_max_fanout 4 [get_ports {x1_bit[7]}]
set_max_fanout 4 [get_ports {x1_bit[6]}]
set_max_fanout 4 [get_ports {x1_bit[5]}]
set_max_fanout 4 [get_ports {x1_bit[4]}]
set_max_fanout 4 [get_ports {x1_bit[3]}]
set_max_fanout 4 [get_ports {x1_bit[2]}]
set_max_fanout 4 [get_ports {x1_bit[1]}]
set_max_fanout 4 [get_ports {x1_bit[0]}]
set_max_fanout 4 [get_ports {x2_bit[7]}]
set_max_fanout 4 [get_ports {x2_bit[6]}]
set_max_fanout 4 [get_ports {x2_bit[5]}]
set_max_fanout 4 [get_ports {x2_bit[4]}]
set_max_fanout 4 [get_ports {x2_bit[3]}]
set_max_fanout 4 [get_ports {x2_bit[2]}]
set_max_fanout 4 [get_ports {x2_bit[1]}]
set_max_fanout 4 [get_ports {x2_bit[0]}]
set_max_fanout 4 [get_ports {x3_bit[7]}]
set_max_fanout 4 [get_ports {x3_bit[6]}]
set_max_fanout 4 [get_ports {x3_bit[5]}]
set_max_fanout 4 [get_ports {x3_bit[4]}]
set_max_fanout 4 [get_ports {x3_bit[3]}]
set_max_fanout 4 [get_ports {x3_bit[2]}]
set_max_fanout 4 [get_ports {x3_bit[1]}]
set_max_fanout 4 [get_ports {x3_bit[0]}]
set_max_fanout 4 [get_ports {x4_bit[7]}]
set_max_fanout 4 [get_ports {x4_bit[6]}]
set_max_fanout 4 [get_ports {x4_bit[5]}]
set_max_fanout 4 [get_ports {x4_bit[4]}]
set_max_fanout 4 [get_ports {x4_bit[3]}]
set_max_fanout 4 [get_ports {x4_bit[2]}]
set_max_fanout 4 [get_ports {x4_bit[1]}]
set_max_fanout 4 [get_ports {x4_bit[0]}]
set_max_fanout 4 [get_ports {x5_bit[7]}]
set_max_fanout 4 [get_ports {x5_bit[6]}]
set_max_fanout 4 [get_ports {x5_bit[5]}]
set_max_fanout 4 [get_ports {x5_bit[4]}]
set_max_fanout 4 [get_ports {x5_bit[3]}]
set_max_fanout 4 [get_ports {x5_bit[2]}]
set_max_fanout 4 [get_ports {x5_bit[1]}]
set_max_fanout 4 [get_ports {x5_bit[0]}]
set_max_fanout 4 [get_ports {x6_bit[7]}]
set_max_fanout 4 [get_ports {x6_bit[6]}]
set_max_fanout 4 [get_ports {x6_bit[5]}]
set_max_fanout 4 [get_ports {x6_bit[4]}]
set_max_fanout 4 [get_ports {x6_bit[3]}]
set_max_fanout 4 [get_ports {x6_bit[2]}]
set_max_fanout 4 [get_ports {x6_bit[1]}]
set_max_fanout 4 [get_ports {x6_bit[0]}]
set_max_fanout 4 [get_ports {x7_bit[7]}]
set_max_fanout 4 [get_ports {x7_bit[6]}]
set_max_fanout 4 [get_ports {x7_bit[5]}]
set_max_fanout 4 [get_ports {x7_bit[4]}]
set_max_fanout 4 [get_ports {x7_bit[3]}]
set_max_fanout 4 [get_ports {x7_bit[2]}]
set_max_fanout 4 [get_ports {x7_bit[1]}]
set_max_fanout 4 [get_ports {x7_bit[0]}]
set_max_fanout 4 [get_ports {x8_bit[7]}]
set_max_fanout 4 [get_ports {x8_bit[6]}]
set_max_fanout 4 [get_ports {x8_bit[5]}]
set_max_fanout 4 [get_ports {x8_bit[4]}]
set_max_fanout 4 [get_ports {x8_bit[3]}]
set_max_fanout 4 [get_ports {x8_bit[2]}]
set_max_fanout 4 [get_ports {x8_bit[1]}]
set_max_fanout 4 [get_ports {x8_bit[0]}]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.01 [get_clocks clk]
set_clock_transition -max -fall 0.01 [get_clocks clk]
set_clock_transition -min -rise 0.01 [get_clocks clk]
set_clock_transition -min -fall 0.01 [get_clocks clk]
set_input_delay -clock clk  0.05  [get_ports reset]
set_input_delay -clock clk  0.05  [get_ports {x1_bit[7]}]
set_input_delay -clock clk  0.05  [get_ports {x1_bit[6]}]
set_input_delay -clock clk  0.05  [get_ports {x1_bit[5]}]
set_input_delay -clock clk  0.05  [get_ports {x1_bit[4]}]
set_input_delay -clock clk  0.05  [get_ports {x1_bit[3]}]
set_input_delay -clock clk  0.05  [get_ports {x1_bit[2]}]
set_input_delay -clock clk  0.05  [get_ports {x1_bit[1]}]
set_input_delay -clock clk  0.05  [get_ports {x1_bit[0]}]
set_input_delay -clock clk  0.05  [get_ports {x2_bit[7]}]
set_input_delay -clock clk  0.05  [get_ports {x2_bit[6]}]
set_input_delay -clock clk  0.05  [get_ports {x2_bit[5]}]
set_input_delay -clock clk  0.05  [get_ports {x2_bit[4]}]
set_input_delay -clock clk  0.05  [get_ports {x2_bit[3]}]
set_input_delay -clock clk  0.05  [get_ports {x2_bit[2]}]
set_input_delay -clock clk  0.05  [get_ports {x2_bit[1]}]
set_input_delay -clock clk  0.05  [get_ports {x2_bit[0]}]
set_input_delay -clock clk  0.05  [get_ports {x3_bit[7]}]
set_input_delay -clock clk  0.05  [get_ports {x3_bit[6]}]
set_input_delay -clock clk  0.05  [get_ports {x3_bit[5]}]
set_input_delay -clock clk  0.05  [get_ports {x3_bit[4]}]
set_input_delay -clock clk  0.05  [get_ports {x3_bit[3]}]
set_input_delay -clock clk  0.05  [get_ports {x3_bit[2]}]
set_input_delay -clock clk  0.05  [get_ports {x3_bit[1]}]
set_input_delay -clock clk  0.05  [get_ports {x3_bit[0]}]
set_input_delay -clock clk  0.05  [get_ports {x4_bit[7]}]
set_input_delay -clock clk  0.05  [get_ports {x4_bit[6]}]
set_input_delay -clock clk  0.05  [get_ports {x4_bit[5]}]
set_input_delay -clock clk  0.05  [get_ports {x4_bit[4]}]
set_input_delay -clock clk  0.05  [get_ports {x4_bit[3]}]
set_input_delay -clock clk  0.05  [get_ports {x4_bit[2]}]
set_input_delay -clock clk  0.05  [get_ports {x4_bit[1]}]
set_input_delay -clock clk  0.05  [get_ports {x4_bit[0]}]
set_input_delay -clock clk  0.05  [get_ports {x5_bit[7]}]
set_input_delay -clock clk  0.05  [get_ports {x5_bit[6]}]
set_input_delay -clock clk  0.05  [get_ports {x5_bit[5]}]
set_input_delay -clock clk  0.05  [get_ports {x5_bit[4]}]
set_input_delay -clock clk  0.05  [get_ports {x5_bit[3]}]
set_input_delay -clock clk  0.05  [get_ports {x5_bit[2]}]
set_input_delay -clock clk  0.05  [get_ports {x5_bit[1]}]
set_input_delay -clock clk  0.05  [get_ports {x5_bit[0]}]
set_input_delay -clock clk  0.05  [get_ports {x6_bit[7]}]
set_input_delay -clock clk  0.05  [get_ports {x6_bit[6]}]
set_input_delay -clock clk  0.05  [get_ports {x6_bit[5]}]
set_input_delay -clock clk  0.05  [get_ports {x6_bit[4]}]
set_input_delay -clock clk  0.05  [get_ports {x6_bit[3]}]
set_input_delay -clock clk  0.05  [get_ports {x6_bit[2]}]
set_input_delay -clock clk  0.05  [get_ports {x6_bit[1]}]
set_input_delay -clock clk  0.05  [get_ports {x6_bit[0]}]
set_input_delay -clock clk  0.05  [get_ports {x7_bit[7]}]
set_input_delay -clock clk  0.05  [get_ports {x7_bit[6]}]
set_input_delay -clock clk  0.05  [get_ports {x7_bit[5]}]
set_input_delay -clock clk  0.05  [get_ports {x7_bit[4]}]
set_input_delay -clock clk  0.05  [get_ports {x7_bit[3]}]
set_input_delay -clock clk  0.05  [get_ports {x7_bit[2]}]
set_input_delay -clock clk  0.05  [get_ports {x7_bit[1]}]
set_input_delay -clock clk  0.05  [get_ports {x7_bit[0]}]
set_input_delay -clock clk  0.05  [get_ports {x8_bit[7]}]
set_input_delay -clock clk  0.05  [get_ports {x8_bit[6]}]
set_input_delay -clock clk  0.05  [get_ports {x8_bit[5]}]
set_input_delay -clock clk  0.05  [get_ports {x8_bit[4]}]
set_input_delay -clock clk  0.05  [get_ports {x8_bit[3]}]
set_input_delay -clock clk  0.05  [get_ports {x8_bit[2]}]
set_input_delay -clock clk  0.05  [get_ports {x8_bit[1]}]
set_input_delay -clock clk  0.05  [get_ports {x8_bit[0]}]
set_output_delay -clock clk  0.05  [get_ports {sum[31]}]
set_output_delay -clock clk  0.05  [get_ports {sum[30]}]
set_output_delay -clock clk  0.05  [get_ports {sum[29]}]
set_output_delay -clock clk  0.05  [get_ports {sum[28]}]
set_output_delay -clock clk  0.05  [get_ports {sum[27]}]
set_output_delay -clock clk  0.05  [get_ports {sum[26]}]
set_output_delay -clock clk  0.05  [get_ports {sum[25]}]
set_output_delay -clock clk  0.05  [get_ports {sum[24]}]
set_output_delay -clock clk  0.05  [get_ports {sum[23]}]
set_output_delay -clock clk  0.05  [get_ports {sum[22]}]
set_output_delay -clock clk  0.05  [get_ports {sum[21]}]
set_output_delay -clock clk  0.05  [get_ports {sum[20]}]
set_output_delay -clock clk  0.05  [get_ports {sum[19]}]
set_output_delay -clock clk  0.05  [get_ports {sum[18]}]
set_output_delay -clock clk  0.05  [get_ports {sum[17]}]
set_output_delay -clock clk  0.05  [get_ports {sum[16]}]
set_output_delay -clock clk  0.05  [get_ports {sum[15]}]
set_output_delay -clock clk  0.05  [get_ports {sum[14]}]
set_output_delay -clock clk  0.05  [get_ports {sum[13]}]
set_output_delay -clock clk  0.05  [get_ports {sum[12]}]
set_output_delay -clock clk  0.05  [get_ports {sum[11]}]
set_output_delay -clock clk  0.05  [get_ports {sum[10]}]
set_output_delay -clock clk  0.05  [get_ports {sum[9]}]
set_output_delay -clock clk  0.05  [get_ports {sum[8]}]
set_output_delay -clock clk  0.05  [get_ports {sum[7]}]
set_output_delay -clock clk  0.05  [get_ports {sum[6]}]
set_output_delay -clock clk  0.05  [get_ports {sum[5]}]
set_output_delay -clock clk  0.05  [get_ports {sum[4]}]
set_output_delay -clock clk  0.05  [get_ports {sum[3]}]
set_output_delay -clock clk  0.05  [get_ports {sum[2]}]
set_output_delay -clock clk  0.05  [get_ports {sum[1]}]
set_output_delay -clock clk  0.05  [get_ports {sum[0]}]
